# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [db_provider, in_memory]
                
        in_memory:
            memory:
                users:
                    admin:  
                        password: $2y$12$boqY0eVVF5t2gCtp3tZ.S.uvtveqedHmx3KO9uYgWanZPhBEbgHtS
                        roles: 'ROLE_ADMIN'
                        
        db_provider:
            entity:
                class: AppBundle:Player
                property: username

    access_control:
        - { path: /events, roles: ROLE_USER }       
        - { path: /teams, roles: ROLE_USER }
        
        - { path: /sports, roles: ROLE_ADMIN }
        - { path: /events/delete, roles: ROLE_ADMIN }
        - { path: /teams/delete, roles: ROLE_ADMIN }
        - { path: /events/create, roles: ROLE_ADMIN }
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: event_list
            provider: chain_provider
            logout:
                path:   logout
                target: login

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
   
            
    encoders:
        AppBundle\Entity\Player:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER